// Shared market → Supabase table mapping.
// Imported by Sparkline and any hook that needs to know where price data lives.
export const SPARKLINE_CONFIG = {
  "H100-GPU-PERP":         { table: "price_data",            priceField: "price",           timeField: "timestamp" },
  "H100-PERP":             { table: "price_data",            priceField: "price",           timeField: "timestamp" },
  "B200-PERP-V2":          { table: "b200_index_prices",      priceField: "index_price" },
  "B200-PERP":             { table: "b200_index_prices",      priceField: "index_price" },
  "AWS-B200-PERP":         { table: "b200_provider_prices",   priceField: "effective_price", providerFilter: "AWS" },
  "ORACLE-B200-PERP":      { table: "b200_provider_prices",   priceField: "effective_price", providerFilter: "Oracle" },
  "COREWEAVE-B200-PERP":   { table: "b200_provider_prices",   priceField: "effective_price", providerFilter: "CoreWeave" },
  "GCP-B200-PERP":         { table: "b200_provider_prices",   priceField: "effective_price", providerFilter: "Google Cloud" },
  "H200-PERP-V2":          { table: "h200_index_prices",      priceField: "index_price" },
  "H200-PERP":             { table: "h200_index_prices",      priceField: "index_price" },
  "T4-PERP":               { table: "t4_index_prices",        priceField: "index_price" },
  "ORACLE-H200-PERP":      { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "Oracle" },
  "ORACLE-H200-PERPETUAL": { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "Oracle" },
  "AWS-H200-PERP":         { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "AWS" },
  "AWS-H200-PERPETUAL":    { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "AWS" },
  "GCP-H200-PERP":         { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "Google Cloud" },
  "GCP-H200-PERPETUAL":    { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "Google Cloud" },
  "COREWEAVE-H200-PERP":   { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "CoreWeave" },
  "COREWEAVE-H200-PERPETUAL": { table: "h200_provider_prices", priceField: "effective_price", providerFilter: "CoreWeave" },
  "AZURE-H200-PERPETUAL":  { table: "h200_provider_prices",   priceField: "effective_price", providerFilter: "Azure" },
  "AWS-H100-PERP":         { table: "h100_hyperscaler_prices", priceField: "effective_price", providerFilter: "Amazon Web Services" },
  "AZURE-H100-PERP":       { table: "h100_hyperscaler_prices", priceField: "effective_price", providerFilter: "Microsoft Azure" },
  "GCP-H100-PERP":         { table: "h100_hyperscaler_prices", priceField: "effective_price", providerFilter: "Google Cloud" },
  "H100-HyperScalers-PERP": { table: "h100_hyperscaler_prices", priceField: "effective_price" },
  "H100-non-HyperScalers-PERP-V2": { table: "price_data",    priceField: "price",           timeField: "timestamp" },
  "H100-non-HyperScalers-PERP": { table: "price_data",       priceField: "price",           timeField: "timestamp" },
  "A100-PERP":             { table: "a100_index_prices",      priceField: "index_price" },
  "ETH-PERP-V2":           { table: "price_data",            priceField: "price",           timeField: "timestamp" },
};
